FROM ghcr.io/ultramarine-linux/desktop-bootc:main
COPY . /usr/src/ultramarine-bootc/tier1/plasma
# Milou is required module for KRunner, upstream packaging forgot to depend
RUN --mount=type=cache,target=/var/cache dnf do -y \
    --no-best \
    --allowerasing \
    --action=remove \
    ultramarine-release-identity-basic \
    --action=install \
    ultramarine-release-identity-plasma \
    plasma-discover-flatpak \
    plasma-discover-packagekit \
    @ultramarine-plasma-product-environment \
    @ultramarine-plasma-no-flatpak-apps \
    plasma-milou \
    --exclude='desktop-backgrounds*' \
    --setopt=install_weak_deps=False

    
# HACK:
# for some reason qtvirtualkeyboard is not getting installed properly
# but it is required for plasma-keyboard to actually work
RUN --mount=type=cache,target=/var/cache dnf do -y \
    --action=reinstall \
    qt6-qtvirtualkeyboard
    
RUN sed -i 's/^livesys_session=.*/livesys_session="kde"/' /etc/sysconfig/livesys


LABEL readymade.prettyname="Ultramarine Plasma Edition"
