FROM ghcr.io/ultramarine-linux/desktop-bootc:main
COPY . /usr/src/ultramarine-bootc/tier1/plasma
RUN --mount=type=cache,target=/var/cache dnf do -y \
    --no-best \
    --allowerasing \
    --action=remove \
    ultramarine-release-identity-basic \
    --action=install \
    ultramarine-release-identity-plasma \
    plasma-discover-flatpak \
    plasma-discover-packagekit \
    @ultramarine-plasma-product-environment \
    --exclude='desktop-backgrounds*' \
    --setopt=install_weak_deps=False

RUN sed -i 's/^livesys_session=.*/livesys_session="kde"/' /etc/sysconfig/livesys


LABEL readymade.prettyname="Ultramarine Plasma Edition"
