FROM ghcr.io/ultramarine-linux/base-bootc:latest

RUN --mount=type=cache,target=/var/cache dnf do -y \
    --no-best \
    --allowerasing \
    --action=remove \
    ultramarine-release-identity-basic \
    --action=install \
    ultramarine-release-identity-xfce \
    taidan \
    @ultramarine-xfce-product-environment

RUN mkdir -p /usr/share/rpm && \
    find /usr/lib/sysimage/rpm -type f -exec sh -c 'set -e; ln -vf "$1" "/usr/share/rpm/$(basename "$1")"' _ {} \;
