FROM ghcr.io/terrapkg/builder:f41 AS builder

WORKDIR /work

RUN \
 --mount=type=cache,target=/var/cache \
 dnf5 install -y yq podman moby-engine rpm-ostree melody just python3-pip pkg-config wget ostree ostree-devel rpm-ostree git hfsplus-tools flatpak dbus dbus-daemon rpmdevtools make mock selinux-policy python3-pip jq @development-tools gcc cairo-devel python3-devel 'pkgconfig(gobject-introspection-1.0)' 'pkgconfig(cairo-gobject)' 'dnf-command(config-manager)'


COPY . .

RUN --mount=type=cache,target=/var/cache \
    melody compile ultramarine/base.yaml out/base

RUN \
  --mount=type=cache,target=/cache \
  --mount=type=bind,rw=true,src=.,dst=/buildcontext,bind-propagation=shared \
  rpm-ostree compose install \
    --repo=/cache/repo \
    out/base/0.yaml /target-rootfs


# Please build from the root directory of the repository

FROM scratch
COPY --from=builder /target-rootfs/ /
LABEL containers.bootc 1
LABEL bootc.diskimage-builder quay.io/centos-bootc/bootc-image-builder
ENV container=oci
# Need to reference builder here to force ordering. But since we have to run
# something anyway, we might as well cleanup after ourselves.
STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]
