[Match]
Architecture=arm64

[Contents]
Packages=
    grub2-efi-aa64
    grub2-efi-aa64-modules
    grub2-efi-aa64-cdboot
    shim-aa64
    shim-unsigned-aarch64
    bcm283x-firmware
    bcm283x-overlays
    "@arm-tools"
