[Build]
SandboxTrees=
    repodir/kaibutsu.repo:/etc/yum.repos.d/kaibutsu.repo
    repodir/linux-surface.repo:/etc/yum.repos.d/linux-surface.repo
    repodir/terra-extras.repo:/etc/yum.repos.d/terra-extras.repo
    repodir/terra-mesa.repo:/etc/yum.repos.d/terra-mesa.repo
    repodir/terra.repo:/etc/yum.repos.d/terra.repo
    repodir/ultramarine-bootc.repo:/etc/yum.repos.d/ultramarine-bootc.repo
    repodir/ultramarine.repo:/etc/yum.repos.d/ultramarine.repo

[Distribution]
Repositories=ultramarine

[Content]
Packages=
    bootc
    bootupd
    @core
    dnf
    dnf5-plugins
    dnf-bootc
    grub2-tools
    iscsi-initiator-utils
    kernel
    kernel-devel-matched
    libdnf5-plugin-actions
    libdnf5-plugin-appstream
    libiscsi-utils
    lvm2
    ostree
    ostree-grub2
    rpm-ostree
    rsync
    shadow-utils
    @standard
    systemd-boot-unsigned
    system-reinstall-bootc
    terra-release
    terra-release-extras
    terra-release-mesa
    tpm2-tools
    ultramarine-logos
    ultramarine-release
    ultramarine-release-common
    ultramarine-release-identity-basic
    ultramarine-repos
