[Build]
ToolsTree=default
ToolsTreeDistribution=fedora
ToolsTreeRelease=44
History=yes
CacheDirectory=mkosi.cache
SandboxTrees=
    ../../base/repodir/ultramarine.repo:/etc/yum.repos.d/ultramarine.repo
