[Output]
ImageId=Ultramarine Linux
OutputDirectory=mkosi.output
ManifestFormat=json
Output=%i_%a
OciLabels=
    containers.bootc=1
    bootc.diskimage-builder=quay.io/centos-bootc/bootc-image-builder
Format=oci
