FROM ghcr.io/ultramarine-linux/base-bootc:main

RUN --mount=type=cache,target=/var/cache dnf do -y \
    --no-best \
    --allowerasing \
    --action install \
    taidan \
    readymade \
    @multimedia \
    @ultramarine-product-common \
    @base-graphical && \
    dnf clean all

RUN systemctl set-default graphical.target
RUN systemctl enable taidan-initial-setup.service