FROM ghcr.io/ultramarine-linux/base-bootc:main

COPY . /usr/src/ultramarine-bootc/tier0/desktop

COPY 20-rhgb.toml /usr/lib/bootc/kargs.d/
RUN --mount=type=cache,target=/var/cache dnf do -y \
    --no-best \
    --allowerasing \
    --action install \
    taidan \
    readymade \
    readymade-config-ultramarine \
    @multimedia \
    @ultramarine-product-common \
    plymouth \
    livesys-scripts \
    isomd5sum \
    orca \
    espeak-ng \
    speech-dispatcher-espeak-ng \
    mkfstab \
    um \
    dive \
    dracut-live \
    dracut-network \
    ultramarine-repos-extras \
    dracut-strip-trigger \
    plymouth-system-theme \
    @base-graphical && \
    dnf clean all


RUN plymouth-set-default-theme bgrt
# Recreate initramfs to add plymouth back
RUN sh -c 'export KERNEL_VERSION="$(basename "$(find /usr/lib/modules -maxdepth 1 -type d | grep -v -E "*.img" | tail -n 1)")" && \
    dracut --force --no-hostonly --force-add plymouth --force-drivers erofs --reproducible --zstd --kver "$KERNEL_VERSION"  "/usr/lib/modules/$KERNEL_VERSION/initramfs.img"'


COPY desktop.sh /tmp/desktop.sh
RUN --mount=type=cache,target=/var/cache sh -c '/tmp/desktop.sh && rm -f /tmp/desktop.sh'

COPY live-setup.sh /tmp/live-setup.sh

RUN chmod +x /tmp/live-setup.sh && \
    sh -c '/tmp/live-setup.sh && rm -f /tmp/live-setup.sh'
