ARG MAJOR_VERSION="${MAJOR_VERSION:-41}"

FROM ghcr.io/ultramarine-linux/base-bootc:$MAJOR_VERSION

RUN dnf install \
  -x PackageKit \
  -x PackageKit-command-not-found \
  -x grubby \
  -x sdubby \
  -x gnome-software-fedora-langpacks \
  -x gnome-software-rpm-ostree \
  --allowerasing -y \
  @ultramarine-gnome-product-environment

