FROM ghcr.io/ultramarine-linux/base-bootc:latest

RUN rm -rf /root # workaround

RUN dnf4 install -x PackageKit -x grubby -x sdubby -x gnome-software-fedora-langpacks --allowerasing -y @ultramarine-gnome-product-environment

RUN dnf4 clean all
