FROM ghcr.io/ultramarine-linux/desktop-bootc:latest

RUN --mount=type=cache,target=/var/cache dnf do -y \
    --no-best \
    --allowerasing \
    --action=remove \
        ultramarine-release-identity-basic \
    --action=install \
        ultramarine-release-identity-gnome \
        gnome-software-rpm-ostree \
        @gnome-desktop \
        @ultramarine-gnome-product-environment \
        gnome-tweaks
