FROM ghcr.io/ultramarine-linux/desktop-bootc:latest
COPY . /usr/src/ultramarine-bootc/tier1/gnome

RUN --mount=type=cache,target=/var/cache dnf do -y \
    --no-best \
    --allowerasing \
    --action=remove \
        ultramarine-release-identity-basic \
    --action=install \
        ultramarine-release-identity-gnome \
        @gnome-desktop \
        @ultramarine-gnome-product-environment \
        gnome-tweaks


LABEL readymade.prettyname="Ultramarine GNOME Edition"