# todo: Build base image from scratch with melody

FROM quay.io/fedora/fedora-bootc:41
# do not cache this layer
RUN --mount=type=cache,target=/tmp/cache:none dnf update -y -x kernel*

RUN dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
RUN dnf install -y --repofrompath "terra,https://repos.fyralabs.com/terra$(rpm -E %fedora)" --setopt="terra.gpgkey=https://repos.fyralabs.com/terra$(rpm -E %fedora)/key.asc" terra-release
RUN dnf install -y --repofrompath "ultramarine,https://repos.fyralabs.com/um$(rpm -E %fedora)/" --setopt="ultramarine.gpgkey=https://repos.fyralabs.com/terra$(rpm -E %fedora)/key.asc" ultramarine-repos-common ultramarine-repos

RUN dnf swap -y --allowerasing fedora-release-common ultramarine-release-identity-basic
RUN dnf swap -y fedora-logos ultramarine-logos

# Remove existing kernel
RUN for pkg in kernel kernel-core kernel-modules kernel-modules-core ; do rpm --erase $pkg --nodeps ; done

# reinstall kernel modules and stuff for the new kernel, install new kernel in case the old one was removed
# Also install some extra packages :3
RUN dnf install -y kernel kernel-core kernel-modules{,-core,-extra} linux-firmware fwupd fwupd-efi @ultramarine-product-common

# (why isnt this here?)
RUN rm -rf /root

# Regenerate initramfs for new kernel
RUN dracut -fv --regenerate-all

# Lint the container for any faulty changes
RUN bootc container lint
