# todo: Build base image from scratch with melody

ARG MAJOR_VERSION="${MAJOR_VERSION:-41}"

FROM quay.io/fedora/fedora-bootc:$MAJOR_VERSION

RUN dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
RUN dnf install -y --repofrompath "terra,https://repos.fyralabs.com/terra$(rpm -E %fedora)" --setopt="terra.gpgkey=https://repos.fyralabs.com/terra$(rpm -E %fedora)/key.asc" terra-release
RUN dnf install -y --repofrompath "ultramarine,https://repos.fyralabs.com/um$(rpm -E %fedora)/" --setopt="ultramarine.gpgkey=https://repos.fyralabs.com/um$(rpm -E %fedora)/key.asc" ultramarine-repos-common ultramarine-repos

RUN dnf swap -y --allowerasing fedora-release-common ultramarine-release-identity-basic
RUN dnf swap -y fedora-logos ultramarine-logos

# reinstall kernel modules and stuff for the new kernel
# Also install some extra packages :3
RUN dnf update -y kernel kernel-core kernel-modules{,-core} && \
  dnf install -y kernel-modules-extra linux-firmware fwupd fwupd-efi @ultramarine-product-common

# Regenerate initramfs for new kernel
RUN dracut --no-hostonly --kver "$(rpm -q kernel | sed 's/kernel-//')" --reproducible --zstd -v --add ostree -f "/lib/modules/$(rpm -q kernel | sed 's/kernel-//')/initramfs.img"

# These are straight up not necessary on bootc containers
RUN rm -rf /var /boot && mkdir -p /var/roothome /boot /root

# Lint the container for any faulty changes
RUN bootc container lint
