[Config]
MinimumVersion=26~devel

[Distribution]
Distribution=fedora
Release=43

[Build]
ToolsTree=default
History=yes
CacheDirectory=mkosi.cache
Incremental=yes

[Validation]
SecureBoot=no
SignExpectedPcr=no


[Content]
# We want to use the bootc/ostree dracut modules instead of letting mkosi handle this. Please reconsider once arbitrary content can be added to the initramfs somehow
Bootable=no
KernelCommandLine=
RemoveFiles=
    /usr/etc
    /var/
    /boot/*

[Output]
ImageId=Ultramarine Linux
OutputDirectory=mkosi.output
ManifestFormat=json
Output=%i_%v_%a
OciLabels=
    containers.bootc=1
    bootc.diskimage-builder=quay.io/centos-bootc/bootc-image-builder
Format=oci
