#!/bin/bash
# This script simply just hardlinks/copies the RPM database to /usr/share/rpm
# so that other tools like rpm-ostree can interact with the standard RPM database.

# Might not be needed when rpm-ostree is finally replaced with dnf5 in CoreOS
RPM_MUT_DB="/usr/lib/sysimage/rpm"
RPM_OSTREE_DB="/usr/share/rpm"

# Check if we are in a live environment
is_live_env() {
    # check /proc/cmdline for rd.live.image
    grep -q "rd.live.image" /proc/cmdline
}

is_in_container() {
    if [ -n "$container" ]; then
        return 0 # true
    else
        return 1 # false
    fi
}

is_bootc_env() {
    # If we're in a live environment, we're definitely not in bootc
    if is_live_env; then
        return 1 # false
    else
        if is_in_container; then
            return 1 # false
        fi
    fi

    # Attempt to run bootc status --json

    if command -v bootc >/dev/null 2>&1; then
        bootc status --json >/dev/null 2>&1
        # if doesnt return 0 then we're not in bootc
        if [ $? -eq 0 ]; then
            return 1 # false
        else
            return 0 # true
        fi
    else
        return 1 # false
    fi
}




if ! is_live_env; then
    # Ensure destination directory exists
    install -d "$RPM_OSTREE_DB"

    # Use rsync to synchronize files from SRC_DB to RPM_OSTREE_DB
    rsync -av "$RPM_MUT_DB/" "$RPM_OSTREE_DB/" 1>&2 2>/dev/null
    echo "log.INFO=Synchronized RPM database from $RPM_MUT_DB to $RPM_OSTREE_DB"

    # resore SELinux contexts
    restorecon -RiF / 1>&2 2>/dev/null || true
    echo "log.INFO=Restored SELinux context on $RPM_OSTREE_DB"
else
    echo "log.INFO=In non-bootc environment, skipping restorecon as it's not needed"
fi
