#!/bin/bash
# This script simply just hardlinks/copies the RPM database to /usr/share/rpm
# so that other tools like rpm-ostree can interact with the standard RPM database.

# Might not be needed when rpm-ostree is finally replaced with dnf5 in CoreOS
RPM_MUT_DB="/usr/lib/sysimage/rpm"
RPM_OSTREE_DB="/usr/share/rpm"

# Ensure destination directory exists
install -d "$RPM_OSTREE_DB"

# Use rsync to synchronize files from SRC_DB to RPM_OSTREE_DB
rsync -av "$RPM_MUT_DB/" "$RPM_OSTREE_DB/"
