#!/bin/bash

# Revert the ostree-specific changes made in the Dockerfile, so that the image can be used
# in a standard installation.
#
# This should only be run in a mutable installation context, not in an ostree-booted system.

set -x
source /usr/src/ultramarine-bootc/base/common.sh

: ${ONLINE:=0}

# Remove symlinks created by bootc
rm -rf /opt /root /home /ostree /srv

# remove rechunk-prep action
rm -f /etc/dnf/libdnf5-plugins/actions.d/rechunk-prep.actions

# Recreate the original directories
mkdir -p /home /root /usr/local /srv /opt

# Set proper permissions
chmod 0755 /home /opt /usr/local /srv
chmod 0700 /root

# Remove tmpfiles configuration
rm -f /usr/lib/tmpfiles.d/bootc-base-dirs.conf

# Restore default useradd HOME setting
sed -i '/^HOME=\/var\/home$/d' /etc/default/useradd || true

# Comment out PackageKit ostree backend
sed -i 's/DefaultBackend=.*/#DefaultBackend=/' /etc/PackageKit/PackageKit.conf
if [ "$ONLINE" -eq 1 ]; then
    dnf do --action=install PackageKit-command-not-found --action=reinstall PackageKit appstream-data
    dnf clean all
fi

# Restore PackageKit backend
if [ -f /usr/lib64/qt6/plugins/discover/packagekit-backend.so.disabled ]; then
    mv /usr/lib64/qt6/plugins/discover/packagekit-backend.so.disabled /usr/lib64/qt6/plugins/discover/packagekit-backend.so
fi

KERNEL_VERSION=$(get_kernel_version)

# Reinstall the kernel to restore initramfs and grub entries
kernel-install add $KERNEL_VERSION /lib/modules/$KERNEL_VERSION/vmlinuz

rsync -av /usr/lib/ostree-boot/ /boot/

mkdir -p /boot/efi
# Copy EFI files
rsync -av /usr/lib/efi/*/*/EFI/ /boot/efi/EFI/

# taidan - remove custom config
rm -f /etc/taidan.toml

# copy GRUB files

rsync -av /usr/lib/grub/ /boot/grub2/

if [ -f /run/.containerenv ] || [ -f /.dockerenv ]; then
    # Do not generate grub.cfg or grubenv during a container build. GRUB sees
    # the backing filesystem as "overlay" and cannot canonicalize it as an
    # installable boot device. The external installer runs with the target disk
    # mounted and is responsible for generating GRUB config.
    echo "Skipping GRUB config generation inside container build"
    echo "Run grub2-mkconfig and grub2-editenv from the external installer instead"
else
    # Regenerate GRUB configuration
    grub2-mkconfig -o /boot/grub2/grub.cfg
    grub2-editenv create
    # grub2-editenv set menu_auto_hide=0
fi
