FROM ghcr.io/ultramarine-linux/base-bootc:latest

RUN dnf install \
  -x PackageKit \
  -x PackageKit-command-not-found \
  -x grubby \
  -x sdubby \
  -x gnome-software-fedora-langpacks \
  -x budgie-desktop-defaults \
  --allowerasing -y \
  @ultramarine-flagship-product-environment
