FROM ghcr.io/ultramarine-linux/desktop-bootc:main
COPY . /usr/src/ultramarine-bootc/tier1/xfce
RUN --mount=type=cache,target=/var/cache dnf do -y \
    --no-best \
    --allowerasing \
    --action=remove \
    ultramarine-release-identity-basic \
    --action=install \
    ultramarine-release-identity-xfce \
    @ultramarine-xfce-product-environment \
    --exclude='suppakit-chalermlarp-th-sarabun-psk-fonts' \ 
    --exclude='initial-setup*' \
    --exclude='desktop-backgrounds*' \
    --setopt=install_weak_deps=False

RUN sed -i 's/^livesys_session=.*/livesys_session="xfce"/' /etc/sysconfig/livesys
RUN echo '# Use our XFCE panel config' >> /var/lib/livesys/livesys-session-extra && \
    echo 'cp /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml /home/liveuser/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml' >> /var/lib/livesys/livesys-session-extra

LABEL readymade.prettyname="Ultramarine Xfce Edition"