FROM ghcr.io/ultramarine-linux/desktop-bootc:main

RUN --mount=type=cache,target=/var/cache dnf do -y \
    --no-best \
    --allowerasing \
    --action=remove \
    ultramarine-release-identity-basic \
    --action=install \
    ultramarine-release-identity-xfce \
    @ultramarine-xfce-product-environment \
    --exclude='initial-setup*' \
    --exclude='desktop-backgrounds*' \
    --setopt=install_weak_deps=False

# RUN /usr/libexec/rpmdb-rechunk-prep
RUN sed -i 's/^livesys_session=.*/livesys_session="xfce"/' /etc/sysconfig/livesys
RUN cat >>/var/lib/livesys/livesys-session-extra <<ALLEOF
# Use our XFCE panel config
cp /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml /home/liveuser/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml
ALLEOF