FROM ghcr.io/ultramarine-linux/desktop-bootc:latest
COPY . /usr/src/ultramarine-bootc/tier1/budgie
RUN --mount=type=cache,target=/var/cache dnf do -y \
    --no-best \
    --allowerasing \
    --action=remove \
    ultramarine-release-identity-basic \
    --action=install \
    ultramarine-release-identity-budgie \
    @ultramarine-budgie-product-environment \
    --exclude='budgie-desktop-defaults'

LABEL readymade.prettyname="Ultramarine Budgie Edition"