name: Build Ultramarine XFCE

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 1 * * TUE" # Every Tuesday at 1am UTC
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/reusable-build-image.yml
    secrets: inherit
    with:
      image-name: ultramarine
      flavor: xfce
