name: Build ISO images with katsu
permissions:
  contents: read
  packages: read
on:
  schedule:
    - cron: "0 4 * * *" # every day at 4am UTC
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build-iso:
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64]
        variant:
          - name: gnome
          - name: plasma
          - name: xfce
          - name: budgie
    name: Build ISO images with katsu
    runs-on: ${{ contains(matrix.arch, 'aarch64') && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}

    container:
      image: ghcr.io/fyralabs/katsu:main
      options: --privileged --security-opt seccomp=unconfined -v /usr:/hostusr -v /:/hostfs

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Clean up space before build
        run: |
          df -h
          # Wipe stuff in our host /usr to make some space

          # We don't need the android SDK
          rm -rf /hostfs/usr/local/lib/android
          # We're a Rust shop, not a Haskell shop
          rm -rf /hostfs/usr/local/.ghcup
          rm -rf /hostfs/opt/ghc
          # or Swift either
          rm -rf /hostfs/usr/share/swift
          # nor Java
          rm -rf /hostfs/usr/lib/jvm
          # We don't even use .NET
          rm -rf /hostfs/usr/share/dotnet
          # We don't need tools we're in a container
          rm -rf /hostfs/opt/hostedtoolcache


          echo "After cleanup:"
          df -h
      - name: Install dependencies
        run: |
          dnf install -y just
      - name: Disable zstd:chunked partial pulls
        run: |
          mkdir -p /etc/containers
          cat > /etc/containers/storage.conf <<'EOF'
          [storage]
          driver = "overlay"

          [storage.options.pull_options]
          enable_partial_images = "false"
          EOF
      - name: Normalize tag
        id: normalize
        run: |
          TAG=$(echo "${{ github.ref_name || 'main' }}" | tr '[:upper:]' '[:lower:]' | tr '/' '-')
          TAG=${TAG#um}
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
      - name: Login to GHCR
        env:
          REGISTRY: ghcr.io
          USERNAME: ${{ github.actor }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: printf '%s\n' "$PASSWORD" | podman login -u "$USERNAME" --password-stdin "$REGISTRY"
      - name: Build ISO
        run: |
          set -euxo pipefail
          IMAGE_TAG="ghcr.io/ultramarine-linux/${{ matrix.variant.name }}-bootc:${{ steps.normalize.outputs.tag }}-standard"
          just image_tag="${IMAGE_TAG}" katsu-live
          mv out.iso ./${{ matrix.variant.name }}-${{ matrix.arch }}.iso
      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: iso-artifact-${{ github.run_id }}-${{ matrix.variant.name }}-${{ matrix.arch }}
          path: ./*.iso
          archive: false
          compression-level: 0
