name: Build disk images
permissions:
  contents: read
  packages: read

env:
  IMAGE_SIZE: 24G
  FILESYSTEM: btrfs

on:
  schedule:
    - cron: "0 4 * * *" # every day at 4am UTC
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-disk:
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64]
        variant:
          - name: gnome
            image: ghcr.io/ultramarine-linux/gnome-bootc:44
          - name: plasma
            image: ghcr.io/ultramarine-linux/plasma-bootc:44
          - name: xfce
            image: ghcr.io/ultramarine-linux/xfce-bootc:44
          - name: budgie
            image: ghcr.io/ultramarine-linux/budgie-bootc:44
    name: Build disk images
    runs-on: ${{ contains(matrix.arch, 'aarch64') && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}

    container:
      # image: ${{ matrix.variant.image }}
      image: ghcr.io/fyralabs/katsu:main
      options: --privileged --security-opt seccomp=unconfined -v /usr:/hostusr -v /:/hostfs -v /dev:/dev -v /var/lib/containers:/var/lib/containers

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4
      - name: Clean up space before build
        run: |
          df -h
          # Wipe stuff in our host /usr to make some space
          # We don't need the android SDK
          rm -rf /hostfs/usr/local/lib/android
          # We're a Rust shop, not a Haskell shop
          rm -rf /hostfs/usr/local/.ghcup
          rm -rf /hostfs/opt/ghc
          # or Swift either
          rm -rf /hostfs/usr/share/swift
          # nor Java
          rm -rf /hostfs/usr/lib/jvm
          # We don't even use .NET
          rm -rf /hostfs/usr/share/dotnet
          # We don't need tools we're in a container
          rm -rf /hostfs/opt/hostedtoolcache


          echo "After cleanup:"
          df -h
      - name: Login to GHCR
        env:
          REGISTRY: ghcr.io
          USERNAME: ${{ github.actor }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: printf '%s\n' "$PASSWORD" | sudo podman login -u "$USERNAME" --password-stdin "$REGISTRY"
      - name: Pull image
        run: |
          sudo podman pull "${{ matrix.variant.image }}"
      - name: Build disk image
        run: |
          set -euxo pipefail
          IMAGE_TAG=${{ matrix.variant.image }}
          IMAGE_SIZE=${{ env.IMAGE_SIZE }}
          FILESYSTEM=${{ env.FILESYSTEM }}

          # Create disk image
          fallocate -l $IMAGE_SIZE disk.raw
          # Build disk image using bootc install to-disk

          sudo podman run \
          --rm \
          --privileged \
          --pid=host \
          -v /var/lib/containers:/var/lib/containers \
          -v /dev:/dev \
          -v $PWD:/workdir \
          --security-opt \
          label=type:unconfined_t ${{ matrix.variant.image }} bootc install to-disk /workdir/disk.raw \
            --source-imgref docker://${IMAGE_TAG} \
            --via-loopback \
            --generic-image \
            --filesystem $FILESYSTEM

          xz -9 -T0 disk.raw

          mv disk.raw.xz ./${{ matrix.variant.name }}-${{ matrix.arch }}.img.xz

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: disk-artifact-${{ github.run_id }}-${{ matrix.variant.name }}-${{ matrix.arch }}
          path: ./*.xz
          archive: false
          compression-level: 0
