name: Build and push Docker images

on:
  schedule:
    - cron: "15 14 * * *"
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-base:
    uses: ./.github/workflows/docker-build.yml
    with:
      variant: base
  
  build-all:
    needs: build-base
    strategy:
      fail-fast: false
      matrix:
        variant:
          - gnome
          - flagship
          - xfce
          - kde
      
    uses: ./.github/workflows/docker-build.yml
    with:
      variant: ${{ matrix.variant }}