FROM ghcr.io/ultramarine-linux/plasma-bootc:main



COPY nvidia.sh /tmp/nvidia.sh
    
RUN --mount=type=cache,target=/var/cache /tmp/nvidia.sh

RUN sh -c 'export KERNEL_VERSION="$(basename "$(find /usr/lib/modules -maxdepth 1 -type d | grep -v -E "*.img" | tail -n 1)")" && \
    dracut --force --no-hostonly --reproducible --zstd --kver "$KERNEL_VERSION"  "/usr/lib/modules/$KERNEL_VERSION/initramfs.img"'
